### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by ganondev** [DavidJCobb/eso-ItemTrig#16]
Last update in 2019, and with the new updates rolling up to blackwood, it seems that the mod no longer bootstraps.
Dustman isn't a suitable replacement for the things I have ItemTrig doing.
Is there any hope?

**Comment by DavidJCobb** [comment]
The add-on is not abandoned per se, but I don't play ESO regularly. I'm happy to address bug reports if they are specific and actionable.

I just tested it with ESO's "Allow out-of-date add-ons" option enabled, and I wasn't able to find any issues with ItemTrig. It didn't log errors on startup, it showed up properly in the add-on settings menu, and the predefined "Refine all raw materials automatically" trigger ran as designed.

If the add-on is emitting error messages, please file a new issue report with specific information, including the full and exact text of the error messages, and what you were doing leading up to the error. If the error has no clear cause, or occurs on startup, then I will also need to know your add-on list. You can use [BugCatcher](https://www.esoui.com/downloads/info1083-BugCatcher.html) to get a persistent log of error messages and to review and copy them at your leisure.

**Comment by ganondev** [comment]
Ahh that's good to hear. I realize now also that the tone of my issue probably came off as pushy, so my apologies for that.
I was just hoping to see a response, which has happened now.
Absolutely, I'll work on getting the error details.

I'm also happy to look into fixing these things myself, but I would need some kind of tour of the project given its size.
If you're fine with that, would you mind dropping a directory somewhere in the project?

Thanks in any case.
